# Generated by Django 2.1.3 on 2024-04-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0013_periodictask_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='last_run',
            field=models.DateTimeField(blank=True, editable=False, help_text='Datetime that the schedule last triggered the task to run. Reset to None if enabled is set to False.', null=True, verbose_name='Last Run Datetime'),
        ),
    ]
