# Generated by Django 2.1.3 on 2024-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_periodictask_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='last_expires',
            field=models.DateTimeField(blank=True, editable=False, help_text='Datetime that the schedule last triggered the task to run. Reset to None if enabled is set to False.', null=True, verbose_name='Last Run Datetime'),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='last_start',
            field=models.DateTimeField(blank=True, editable=False, help_text='Datetime that the schedule last triggered the task to run. Reset to None if enabled is set to False.', null=True, verbose_name='Last Run Datetime'),
        ),
    ]
