# Generated by Django 2.1.3 on 2024-04-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_auto_20240405_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodictask',
            name='timezone',
        ),
    ]
